name: coffee_delivery
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  bloc: ^8.1.2
  carousel_slider: ^4.2.1
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  provider: ^6.0.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.6
  freezed: ^2.4.2

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
